import {
  AppNotification,
  Career,
  Child,
  Domain,
  NotificationSettings,
  ParentProfile,
  RiasecType,
} from "./types";

export const RIASEC_LABELS: Record<RiasecType, string> = {
  R: "Réaliste",
  I: "Investigateur",
  A: "Artistique",
  S: "Social",
  E: "Entreprenant",
  C: "Conventionnel",
};

export const DOMAINS: Domain[] = [
  {
    slug: "numerique",
    name: "Numérique",
    icon: "cpu",
    description: "Développement, design digital, data et outils numériques.",
  },
  {
    slug: "agro-transformation",
    name: "Agro-transformation",
    icon: "leaf",
    description: "Transformation des produits agricoles locaux en produits finis.",
  },
  {
    slug: "sante",
    name: "Santé",
    icon: "heartPulse",
    description: "Soin, accompagnement et suivi médical des populations.",
  },
  {
    slug: "business",
    name: "Business",
    icon: "briefcase",
    description: "Entrepreneuriat, gestion, vente et communication.",
  },
  {
    slug: "genie",
    name: "Génie",
    icon: "hardHat",
    description: "Construction, infrastructures et ingénierie de terrain.",
  },
];

export const CAREERS: Career[] = [
  {
    id: "c1",
    slug: "developpeuse-web",
    title: "Développeuse web",
    domain: "Numérique",
    riasec: ["I", "R"],
    summary: "Conçoit et construit des sites et applications.",
    description:
      "La développeuse web transforme des idées en produits numériques concrets : sites, applications, plateformes. Elle travaille avec des langages comme JavaScript, résout des problèmes logiques toute la journée et voit son travail prendre vie à l'écran.",
    videoLength: "48s",
  },
  {
    id: "c2",
    slug: "ingenieure-agro",
    title: "Ingénieure agro-transformation",
    domain: "Agro-transformation",
    riasec: ["R", "I"],
    summary: "Transforme les produits agricoles locaux en produits finis.",
    description:
      "Elle met au point des procédés pour transformer le manioc, l'ananas ou le soja en produits alimentaires prêts à consommer, en veillant à la qualité et à la conservation.",
    videoLength: "52s",
  },
  {
    id: "c3",
    slug: "designer-graphique",
    title: "Designer graphique",
    domain: "Numérique",
    riasec: ["A", "E"],
    summary: "Crée des identités visuelles pour marques et produits.",
    description:
      "Du logo à l'affiche en passant par les interfaces, la designer graphique donne une forme visuelle aux idées. Elle jongle entre créativité, contraintes clients et outils numériques.",
    videoLength: "41s",
  },
  {
    id: "c4",
    slug: "infirmiere",
    title: "Infirmière",
    domain: "Santé",
    riasec: ["S", "R"],
    summary: "Soigne, rassure et accompagne les patients au quotidien.",
    description:
      "Sur le terrain ou en établissement de santé, l'infirmière prodigue des soins, surveille l'état des patients et travaille en équipe avec les médecins.",
    videoLength: "55s",
  },
  {
    id: "c5",
    slug: "entrepreneure",
    title: "Entrepreneure",
    domain: "Business",
    riasec: ["E", "A"],
    summary: "Crée et pilote sa propre entreprise.",
    description:
      "L'entrepreneure identifie une opportunité, construit un produit ou service et bâtit une équipe pour le porter. Un métier fait de prises de décision et de résilience.",
    videoLength: "46s",
  },
  {
    id: "c6",
    slug: "technicien-genie-civil",
    title: "Technicien génie civil",
    domain: "Génie",
    riasec: ["R", "C"],
    summary: "Supervise la construction de routes et bâtiments.",
    description:
      "Il traduit les plans d'architectes et d'ingénieurs en chantiers réels, contrôle la qualité des travaux et coordonne les équipes sur le terrain.",
    videoLength: "50s",
  },
  {
    id: "c7",
    slug: "technicienne-qualite-agroalimentaire",
    title: "Technicienne qualité agroalimentaire",
    domain: "Agro-transformation",
    riasec: ["C", "R"],
    summary: "Contrôle la qualité et la sécurité des produits transformés.",
    description:
      "Elle vérifie à chaque étape de production que les normes d'hygiène et de qualité sont respectées, des matières premières jusqu'au produit fini emballé.",
    videoLength: "44s",
  },
  {
    id: "c8",
    slug: "sage-femme",
    title: "Sage-femme",
    domain: "Santé",
    riasec: ["S", "I"],
    summary: "Accompagne les femmes enceintes avant, pendant et après l'accouchement.",
    description:
      "La sage-femme suit la grossesse, accompagne l'accouchement et conseille les jeunes mères. Un métier d'écoute, de rigueur médicale et de présence humaine.",
    videoLength: "58s",
  },
  {
    id: "c9",
    slug: "community-manager",
    title: "Community manager",
    domain: "Business",
    riasec: ["A", "E"],
    summary: "Anime la présence en ligne d'une marque ou d'une entreprise.",
    description:
      "Il crée du contenu, dialogue avec les communautés en ligne et construit la réputation numérique d'une entreprise sur les réseaux sociaux.",
    videoLength: "39s",
  },
  {
    id: "c10",
    slug: "architecte",
    title: "Architecte",
    domain: "Génie",
    riasec: ["A", "R"],
    summary: "Conçoit des bâtiments qui allient usage, esthétique et solidité.",
    description:
      "De l'esquisse au plan technique, l'architecte imagine des espaces de vie ou de travail, en tenant compte du terrain, du budget et des besoins des habitants.",
    videoLength: "51s",
  },
];

export const PARENT_PROFILE: ParentProfile = {
  firstName: "Prosper",
  lastName: "Zinsou",
  email: "prosper.zinsou@example.com",
  phone: "+229 97 00 00 00",
};

export const CHILDREN: Child[] = [
  {
    id: "e1",
    matricule: "COT-2026-0142",
    firstName: "Aïcha",
    lastName: "Zinsou",
    birthDate: "2012-03-14",
    className: "4ème B",
    school: "Collège Public de Cotonou",
    avatarIcon: "sun",
    riasecDominant: ["R", "I", "A"],
    riasecCompleted: true,
    riasecScores: [
      { type: "R", label: "Réaliste", score: 78 },
      { type: "I", label: "Investigateur", score: 72 },
      { type: "A", label: "Artistique", score: 65 },
      { type: "S", label: "Social", score: 40 },
      { type: "E", label: "Entreprenant", score: 35 },
      { type: "C", label: "Conventionnel", score: 28 },
    ],
    suggestedCareerIds: ["c1", "c2", "c3"],
    exploredCareerIds: ["c1", "c2", "c3", "c6"],
    masteredCareerIds: ["c1"],
    favoriteCareerIds: ["c1", "c3"],
    interestPoints: [
      "Aime résoudre des problèmes concrets",
      "Curieuse des outils numériques",
      "Sensible à la création visuelle",
    ],
    progressPercent: 62,
    badges: [
      {
        id: "b1",
        name: "Métier maîtrisé",
        description: "A validé toutes les étapes de la mission Développeuse web.",
        icon: "trophy",
        dateEarned: "2026-06-24T08:00:00",
      },
      {
        id: "b2",
        name: "Explorateur curieux",
        description: "A exploré au moins 4 métiers différents.",
        icon: "compass",
        dateEarned: "2026-06-19T17:10:00",
      },
      {
        id: "b3",
        name: "Profil dévoilé",
        description: "A complété son test RIASEC.",
        icon: "sparkles",
        dateEarned: "2026-06-05T10:00:00",
      },
      {
        id: "b4",
        name: "Première mission",
        description: "A démarré sa toute première mission métier.",
        icon: "flame",
        dateEarned: "2026-06-06T09:15:00",
      },
    ],
    activity: [
      {
        id: "a1",
        date: "2026-06-24T08:00:00",
        type: "badge_earned",
        label: "A obtenu le badge « Métier maîtrisé » pour Développeuse web.",
        careerId: "c1",
      },
      {
        id: "a2",
        date: "2026-06-24T07:40:00",
        type: "mission_completed",
        label: "A terminé le défi rapide de la mission Développeuse web.",
        careerId: "c1",
      },
      {
        id: "a3",
        date: "2026-06-20T18:05:00",
        type: "career_favorited",
        label: "A ajouté Designer graphique à ses favoris.",
        careerId: "c3",
      },
      {
        id: "a4",
        date: "2026-06-19T17:10:00",
        type: "career_explored",
        label: "A exploré la fiche Technicien génie civil.",
        careerId: "c6",
      },
      {
        id: "a5",
        date: "2026-06-12T12:00:00",
        type: "mission_started",
        label: "A démarré la mission Ingénieure agro-transformation.",
        careerId: "c2",
      },
      {
        id: "a6",
        date: "2026-06-06T09:15:00",
        type: "mission_started",
        label: "A démarré sa première mission métier : Développeuse web.",
        careerId: "c1",
      },
      {
        id: "a7",
        date: "2026-06-05T10:00:00",
        type: "riasec_completed",
        label: "A complété le test RIASEC. Profil dominant : Réaliste, Investigateur, Artistique.",
      },
      {
        id: "a8",
        date: "2026-06-01T08:30:00",
        type: "compte_active",
        label: "Compte activé sur To be.come.",
      },
    ],
    comments: [
      {
        id: "cm1",
        author: "Papa",
        date: "2026-06-10T09:20:00",
        text: "Fière de voir qu'elle s'intéresse au développement web, on en a discuté ce week-end.",
      },
    ],
    identityVerified: true,
  },
  {
    id: "e2",
    matricule: "COT-2026-0143",
    firstName: "Kévin",
    lastName: "Zinsou",
    birthDate: "2010-11-02",
    className: "2nde C",
    school: "Collège Public de Cotonou",
    avatarIcon: "zap",
    riasecDominant: ["E", "S"],
    riasecCompleted: true,
    riasecScores: [
      { type: "E", label: "Entreprenant", score: 80 },
      { type: "S", label: "Social", score: 74 },
      { type: "A", label: "Artistique", score: 55 },
      { type: "R", label: "Réaliste", score: 44 },
      { type: "I", label: "Investigateur", score: 38 },
      { type: "C", label: "Conventionnel", score: 30 },
    ],
    suggestedCareerIds: ["c5", "c4"],
    exploredCareerIds: ["c5", "c4"],
    masteredCareerIds: [],
    favoriteCareerIds: ["c5"],
    interestPoints: [
      "Aime prendre des initiatives",
      "À l'aise pour convaincre et négocier",
    ],
    progressPercent: 35,
    badges: [
      {
        id: "b5",
        name: "Profil dévoilé",
        description: "A complété son test RIASEC.",
        icon: "sparkles",
        dateEarned: "2026-06-22T14:30:00",
      },
    ],
    activity: [
      {
        id: "a9",
        date: "2026-06-22T14:30:00",
        type: "riasec_completed",
        label: "A complété le test RIASEC. Profil dominant : Entreprenant.",
      },
      {
        id: "a10",
        date: "2026-06-22T14:10:00",
        type: "riasec_started",
        label: "A démarré le test RIASEC.",
      },
      {
        id: "a11",
        date: "2026-06-20T11:00:00",
        type: "career_explored",
        label: "A exploré la fiche Entrepreneure.",
        careerId: "c5",
      },
      {
        id: "a12",
        date: "2026-06-18T16:45:00",
        type: "career_explored",
        label: "A exploré la fiche Infirmière.",
        careerId: "c4",
      },
      {
        id: "a13",
        date: "2026-06-14T09:00:00",
        type: "compte_active",
        label: "Compte activé sur To be.come.",
      },
    ],
    comments: [],
    identityVerified: true,
  },
  {
    id: "e3",
    matricule: "COT-2026-0144",
    firstName: "Rachelle",
    lastName: "Zinsou",
    birthDate: "2014-07-22",
    className: "6ème A",
    school: "Collège Public de Cotonou",
    avatarIcon: "palette",
    riasecDominant: [],
    riasecCompleted: false,
    riasecScores: [],
    suggestedCareerIds: [],
    exploredCareerIds: [],
    masteredCareerIds: [],
    favoriteCareerIds: [],
    interestPoints: [],
    progressPercent: 5,
    badges: [],
    activity: [
      {
        id: "a14",
        date: "2026-06-15T09:00:00",
        type: "compte_active",
        label: "Compte activé sur To be.come.",
      },
    ],
    comments: [],
    identityVerified: true,
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    childId: "e1",
    date: "2026-06-24T08:00:00",
    title: "Nouveau badge débloqué",
    message: "Aïcha a obtenu le badge « Métier maîtrisé » pour Développeuse web.",
    read: false,
  },
  {
    id: "n2",
    childId: "e2",
    date: "2026-06-22T14:30:00",
    title: "Profil RIASEC complété",
    message: "Kévin a terminé son test RIASEC. Profil dominant : Entreprenant.",
    read: false,
  },
  {
    id: "n3",
    childId: "e1",
    date: "2026-06-18T10:15:00",
    title: "Nouvelle mission disponible",
    message: "Une nouvelle mission métier a été débloquée pour Aïcha.",
    read: true,
  },
  {
    id: "n4",
    childId: "e3",
    date: "2026-06-15T09:00:00",
    title: "Bienvenue sur To be.come",
    message: "Le compte de Rachelle a été activé. Elle peut commencer son parcours.",
    read: true,
  },
];

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  frequency: "weekly",
  channels: ["in-app", "whatsapp"],
};
